name: Quantum Forge Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Deployment target environment'
        required: true
        default: 'staging'
      quantum_mode:
        description: 'Quantum processing mode'
        required: false
        default: 'auto'

jobs:
  quantum_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Quantum State Analysis
        id: quantum_state
        uses: ./actions/quantum-state
        with:
          mode: ${{ github.event.inputs.quantum_mode || 'auto' }}
          
      - name: Context Processing
        id: context
        run: |
          echo "Processing quantum context..."
          python -m quantum_forge.context_processor
          
  workflow_orchestration:
    needs: quantum_analysis
    runs-on: ubuntu-latest
    steps:
      - name: Orchestrate Workflows
        id: orchestrate
        uses: ./actions/workflow-orchestrator
        with:
          quantum_state: ${{ needs.quantum_analysis.outputs.state }}
          context: ${{ needs.quantum_analysis.outputs.context }}
          
      - name: Execute Workflows
        run: |
          python -m quantum_forge.workflow_executor
          
  deployment:
    needs: workflow_orchestration
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deployment_target }}
    steps:
      - name: Prepare Deployment
        id: prepare
        uses: ./actions/deployment-prep
        with:
          target: ${{ github.event.inputs.deployment_target }}
          
      - name: Execute Deployment
        id: deploy
        uses: ./actions/deployer
        with:
          config: ${{ steps.prepare.outputs.config }}
          
      - name: Verify Deployment
        id: verify
        uses: ./actions/deployment-verify
        with:
          deployment_id: ${{ steps.deploy.outputs.deployment_id }}
          
  notification:
    needs: [quantum_analysis, workflow_orchestration, deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Stakeholders
        uses: ./actions/notifier
        with:
          status: ${{ needs.deployment.outputs.status || 'skipped' }}
          quantum_state: ${{ needs.quantum_analysis.outputs.state }}
          workflows: ${{ needs.workflow_orchestration.outputs.executed_workflows }}